try {
} catch (ArithmeticException e){
	return;
}